WITH delivery(service_code,name,sort_order,is_required) AS (VALUES
('DV_20','Video Brief & mục tiêu',1,TRUE),
('DV_20','Concept / Content Angle',2,TRUE),
('DV_20','Kịch bản',3,TRUE),
('DV_20','Shot List',4,TRUE),
('DV_20','Chuẩn bị sản xuất',5,TRUE),
('DV_20','Quay Video',6,TRUE),
('DV_20','Dựng Video',7,TRUE),
('DV_20','Subtitle / Caption',8,TRUE),
('DV_20','Âm thanh / Nhạc',9,TRUE),
('DV_20','Cover / Thumbnail',10,TRUE),
('DV_20','QA & Export',11,TRUE),
('DV_20','Revision',12,TRUE),
('DV_21','Creative Brief & Funnel Goal',1,TRUE),
('DV_21','Creative Angle',2,TRUE),
('DV_21','Script / Storyboard',3,TRUE),
('DV_21','Shot List / Production Plan',4,TRUE),
('DV_21','Quay / Production',5,TRUE),
('DV_21','Dựng Master Video',6,TRUE),
('DV_21','Motion Graphics / Supers',7,TRUE),
('DV_21','Voice-over / Music / SFX',8,TRUE),
('DV_21','CTA / Subtitle',9,TRUE),
('DV_21','Ad Variants / Cutdowns',10,TRUE),
('DV_21','QA & Export',11,TRUE),
('DV_21','Revision',12,TRUE),
('DV_22','Product Brief & USP',1,TRUE),
('DV_22','Nghiên cứu sản phẩm / claim',2,TRUE),
('DV_22','Review Angle',3,TRUE),
('DV_22','Kịch bản Review',4,TRUE),
('DV_22','Shot Plan',5,TRUE),
('DV_22','Product Staging',6,TRUE),
('DV_22','Quay Video',7,TRUE),
('DV_22','Dựng Video',8,TRUE),
('DV_22','Subtitle / Caption',9,TRUE),
('DV_22','Fact / Claim Check',10,TRUE),
('DV_22','QA & Export',11,TRUE),
('DV_22','Revision',12,TRUE),
('DV_23','Location Brief',1,TRUE),
('DV_23','Nghiên cứu điểm nổi bật',2,TRUE),
('DV_23','Kịch bản / Review Angle',3,TRUE),
('DV_23','Route / Shot Plan',4,TRUE),
('DV_23','Quay tại địa điểm',5,TRUE),
('DV_23','B-roll & Experience Capture',6,TRUE),
('DV_23','Dựng Video',7,TRUE),
('DV_23','Subtitle / Location Info',8,TRUE),
('DV_23','Fact-check thông tin địa điểm',9,TRUE),
('DV_23','QA & Export',10,TRUE),
('DV_23','Revision',11,TRUE),
('DV_24','AI Video Brief',1,TRUE),
('DV_24','Script',2,TRUE),
('DV_24','Storyboard / Scene Plan',3,TRUE),
('DV_24','Visual Reference / Style Guide',4,TRUE),
('DV_24','Prompt Design',5,TRUE),
('DV_24','Generate Visual / Clips',6,TRUE),
('DV_24','Iteration & Character / Style Consistency',7,TRUE),
('DV_24','Voice / Audio',8,TRUE),
('DV_24','Edit & Assembly',9,TRUE),
('DV_24','Subtitle / Motion',10,TRUE),
('DV_24','QA & Export',11,TRUE),
('DV_24','Revision',12,TRUE),
('DV_25','VEO 3 Brief',1,TRUE),
('DV_25','Scene Script / Shot Plan',2,TRUE),
('DV_25','Prompt Pack',3,TRUE),
('DV_25','Reference Assets',4,TRUE),
('DV_25','Generate Scenes / Clips',5,TRUE),
('DV_25','Iteration & Continuity',6,TRUE),
('DV_25','Select & Assemble',7,TRUE),
('DV_25','Voice / Sound Design',8,TRUE),
('DV_25','Edit & Finishing',9,TRUE),
('DV_25','Subtitle / Caption',10,TRUE),
('DV_25','QA & Export',11,TRUE),
('DV_25','Revision',12,TRUE),
('DV_26','Grok Brief & Output Specification',1,TRUE),
('DV_26','Source / Context Research',2,TRUE),
('DV_26','Prompt Framework',3,TRUE),
('DV_26','Content / Asset Generation',4,TRUE),
('DV_26','Output Selection',5,TRUE),
('DV_26','Refinement & Iteration',6,TRUE),
('DV_26','Fact / Consistency Check',7,TRUE),
('DV_26','Asset Assembly / Formatting',8,TRUE),
('DV_26','QA',9,TRUE),
('DV_26','Export / Handover',10,TRUE),
('DV_26','Revision',11,TRUE))
INSERT INTO public.service_delivery_items(service_id,name,sort_order,is_required,active)
SELECT s.id,d.name,d.sort_order,d.is_required,TRUE
FROM delivery d JOIN public.services s ON s.service_code=d.service_code
WHERE NOT EXISTS (SELECT 1 FROM public.service_delivery_items e WHERE e.service_id=s.id AND lower(btrim(e.name))=lower(btrim(d.name)));
