WITH delivery(service_code,name,sort_order,is_required) AS (VALUES
('DV_01','Brief & Scope',1,TRUE),
('DV_01','Sitemap',2,TRUE),
('DV_01','Wireframe',3,TRUE),
('DV_01','UI/UX Figma',4,TRUE),
('DV_01','Responsive Design',5,TRUE),
('DV_01','Development',6,TRUE),
('DV_01','CMS & Data Integration',7,TRUE),
('DV_01','Form / CTA / Tracking',8,TRUE),
('DV_01','SEO Technical Foundation',9,TRUE),
('DV_01','QA & Performance',10,TRUE),
('DV_01','UAT & Go-live',11,TRUE),
('DV_01','Handover',12,TRUE),
('DV_01','Domain / Hosting',13,FALSE),
('DV_01','Nhập liệu nội dung',14,FALSE),
('DV_01','Third-party Integration',15,FALSE),
('DV_02','Brief & mục tiêu chuyển đổi',1,TRUE),
('DV_02','Cấu trúc nội dung Landing Page',2,TRUE),
('DV_02','Wireframe',3,TRUE),
('DV_02','UI Design',4,TRUE),
('DV_02','Responsive Design',5,TRUE),
('DV_02','Development',6,TRUE),
('DV_02','Form / CTA',7,TRUE),
('DV_02','Conversion Tracking',8,TRUE),
('DV_02','QA & Performance',9,TRUE),
('DV_02','UAT & Go-live',10,TRUE),
('DV_02','Copywriting Landing Page',11,FALSE),
('DV_02','Tích hợp CRM / Webhook',12,FALSE),
('DV_02','Domain / Subdomain',13,FALSE),
('DV_03','Audit hiện trạng Website',1,TRUE),
('DV_03','Backup & kiểm tra an toàn',2,TRUE),
('DV_03','Cập nhật CMS / Plugin / Theme',3,TRUE),
('DV_03','Cập nhật nội dung theo yêu cầu',4,TRUE),
('DV_03','Sửa lỗi giao diện / chức năng',5,TRUE),
('DV_03','Kiểm tra Form / Link / CTA',6,TRUE),
('DV_03','Tối ưu hiệu suất định kỳ',7,TRUE),
('DV_03','Kiểm tra bảo mật cơ bản',8,TRUE),
('DV_03','Báo cáo bảo trì định kỳ',9,TRUE),
('DV_03','Phát triển tính năng bổ sung',10,FALSE),
('DV_03','Khôi phục sự cố / Malware',11,FALSE),
('DV_04','SEO Audit tổng thể',1,TRUE),
('DV_04','Nghiên cứu từ khóa & Search Intent',2,TRUE),
('DV_04','Kiến trúc Website & Keyword Mapping',3,TRUE),
('DV_04','Technical SEO',4,TRUE),
('DV_04','On-page SEO',5,TRUE),
('DV_04','Content Plan SEO',6,TRUE),
('DV_04','Tối ưu & xuất bản nội dung SEO',7,TRUE),
('DV_04','Internal Linking',8,TRUE),
('DV_04','Off-page / Authority Building',9,TRUE),
('DV_04','Tracking Search Console / GA4',10,TRUE),
('DV_04','Báo cáo & tối ưu định kỳ',11,TRUE),
('DV_04','Content Refresh',12,FALSE),
('DV_04','CRO hỗ trợ SEO',13,FALSE),
('DV_05','Nhận Brief & mục tiêu nội dung',1,TRUE),
('DV_05','Nghiên cứu từ khóa / chủ đề',2,TRUE),
('DV_05','Xây dựng Outline',3,TRUE),
('DV_05','Nghiên cứu nguồn & dữ liệu',4,TRUE),
('DV_05','Viết nội dung',5,TRUE),
('DV_05','SEO On-page nội dung',6,TRUE),
('DV_05','Hình ảnh / Media đề xuất',7,TRUE),
('DV_05','Internal Linking',8,TRUE),
('DV_05','Biên tập & QA',9,TRUE),
('DV_05','Đăng bài / Bàn giao',10,TRUE),
('DV_05','Theo dõi hiệu suất nội dung',11,FALSE),
('DV_05','Content Refresh',12,FALSE),
('DV_06','Audit Google Business Profile',1,TRUE),
('DV_06','Xác minh & chuẩn hóa NAP',2,TRUE),
('DV_06','Danh mục / Dịch vụ / Thuộc tính',3,TRUE),
('DV_06','Tối ưu mô tả doanh nghiệp',4,TRUE),
('DV_06','Hình ảnh & Media Profile',5,TRUE),
('DV_06','Sản phẩm / Dịch vụ trên Profile',6,TRUE),
('DV_06','Google Posts',7,TRUE),
('DV_06','Review Management Foundation',8,TRUE),
('DV_06','Q&A & thông tin khách hàng',9,TRUE),
('DV_06','Local Keyword Optimization',10,TRUE),
('DV_06','Tracking & Báo cáo Local',11,TRUE),
('DV_06','Citation / NAP Cleanup',12,FALSE),
('DV_07','Audit tài khoản & mục tiêu quảng cáo',1,TRUE),
('DV_07','Conversion Tracking',2,TRUE),
('DV_07','Nghiên cứu từ khóa / nhu cầu',3,TRUE),
('DV_07','Cấu trúc Campaign / Ad Group',4,TRUE),
('DV_07','Ad Copy & Assets',5,TRUE),
('DV_07','Đánh giá Landing Page',6,TRUE),
('DV_07','Thiết lập ngân sách & bidding',7,TRUE),
('DV_07','Launch Campaign',8,TRUE),
('DV_07','Search Terms & Negative Keywords',9,TRUE),
('DV_07','Tối ưu ngân sách / bidding / ads',10,TRUE),
('DV_07','A/B Testing',11,TRUE),
('DV_07','Báo cáo hiệu suất',12,TRUE),
('DV_07','Remarketing',13,FALSE),
('DV_08','Audit Business Manager & mục tiêu',1,TRUE),
('DV_08','Pixel / CAPI / Conversion Tracking',2,TRUE),
('DV_08','Nghiên cứu Audience & Offer',3,TRUE),
('DV_08','Cấu trúc Campaign',4,TRUE),
('DV_08','Creative Plan',5,TRUE),
('DV_08','Ad Copy',6,TRUE),
('DV_08','Thiết lập ngân sách & phân phối',7,TRUE),
('DV_08','Launch Campaign',8,TRUE),
('DV_08','Tối ưu Audience / Creative / Budget',9,TRUE),
('DV_08','Retargeting',10,TRUE),
('DV_08','A/B Testing',11,TRUE),
('DV_08','Báo cáo hiệu suất',12,TRUE),
('DV_08','Landing Page / CRM Integration',13,FALSE),
('DV_09','Audit TikTok Ads & mục tiêu',1,TRUE),
('DV_09','Pixel / Events Tracking',2,TRUE),
('DV_09','Nghiên cứu Audience & Offer',3,TRUE),
('DV_09','Creative Angle & Content Requirement',4,TRUE),
('DV_09','Cấu trúc Campaign',5,TRUE),
('DV_09','Thiết lập ngân sách & bidding',6,TRUE),
('DV_09','Launch Campaign',7,TRUE),
('DV_09','Tối ưu Creative / Audience / Budget',8,TRUE),
('DV_09','Retargeting',9,TRUE),
('DV_09','A/B Testing',10,TRUE),
('DV_09','Báo cáo hiệu suất',11,TRUE),
('DV_09','Landing Page / Shop Integration',12,FALSE))
INSERT INTO public.service_delivery_items(service_id,name,sort_order,is_required,active)
SELECT s.id,d.name,d.sort_order,d.is_required,TRUE
FROM delivery d JOIN public.services s ON s.service_code=d.service_code
WHERE NOT EXISTS (SELECT 1 FROM public.service_delivery_items e WHERE e.service_id=s.id AND lower(btrim(e.name))=lower(btrim(d.name)));
