WITH delivery(service_code,name,sort_order,is_required) AS (VALUES
('DV_10','Audit Fanpage & định vị',1,TRUE),
('DV_10','Content Strategy',2,TRUE),
('DV_10','Content Pillars',3,TRUE),
('DV_10','Lịch nội dung',4,TRUE),
('DV_10','Copywriting',5,TRUE),
('DV_10','Thiết kế Visual',6,TRUE),
('DV_10','Lên lịch & đăng bài',7,TRUE),
('DV_10','Quản trị bình luận / tương tác',8,TRUE),
('DV_10','Theo dõi hiệu suất',9,TRUE),
('DV_10','Báo cáo & tối ưu',10,TRUE),
('DV_10','Quản trị Inbox',11,FALSE),
('DV_10','Phối hợp Campaign / Ads',12,FALSE),
('DV_11','Audit Instagram & Profile Optimization',1,TRUE),
('DV_11','Content Strategy',2,TRUE),
('DV_11','Content Pillars',3,TRUE),
('DV_11','Feed / Visual Direction',4,TRUE),
('DV_11','Lịch nội dung',5,TRUE),
('DV_11','Caption & CTA',6,TRUE),
('DV_11','Thiết kế Post / Carousel / Reel Cover',7,TRUE),
('DV_11','Đăng bài & tối ưu Hashtag / SEO',8,TRUE),
('DV_11','Community Engagement',9,TRUE),
('DV_11','Báo cáo & tối ưu',10,TRUE),
('DV_11','Reels Production',11,FALSE),
('DV_12','Audit kênh & định vị',1,TRUE),
('DV_12','Content Pillars',2,TRUE),
('DV_12','Series / Format nội dung',3,TRUE),
('DV_12','Lịch nội dung TikTok',4,TRUE),
('DV_12','Kịch bản Video',5,TRUE),
('DV_12','Hướng dẫn / tổ chức quay',6,TRUE),
('DV_12','Edit Video',7,TRUE),
('DV_12','Caption / SEO TikTok / Hashtag',8,TRUE),
('DV_12','Đăng bài',9,TRUE),
('DV_12','Community Management',10,TRUE),
('DV_12','Báo cáo & tối ưu nội dung',11,TRUE),
('DV_12','Livestream Plan',12,FALSE),
('DV_13','Đánh giá điều kiện xác minh',1,TRUE),
('DV_13','Audit & chuẩn hóa Fanpage',2,TRUE),
('DV_13','Thu thập hồ sơ xác minh',3,TRUE),
('DV_13','Chuẩn hóa nhận diện / thông tin pháp lý',4,TRUE),
('DV_13','Chuẩn bị hồ sơ yêu cầu',5,TRUE),
('DV_13','Nộp yêu cầu xác minh',6,TRUE),
('DV_13','Theo dõi phản hồi nền tảng',7,TRUE),
('DV_13','Bổ sung hồ sơ khi cần',8,TRUE),
('DV_13','Bàn giao kết quả',9,TRUE),
('DV_13','PR hỗ trợ độ nổi bật thương hiệu',10,FALSE),
('DV_13','Security Hardening Fanpage',11,FALSE),
('DV_14','Đánh giá Fanpage & tài sản',1,TRUE),
('DV_14','Kiểm tra quyền sở hữu / quyền quản trị',2,TRUE),
('DV_14','Kiểm tra rủi ro & tuân thủ',3,TRUE),
('DV_14','Xác nhận phạm vi tài sản bàn giao',4,TRUE),
('DV_14','Thỏa thuận & hồ sơ giao dịch',5,TRUE),
('DV_14','Chuyển quyền quản trị',6,TRUE),
('DV_14','Security Handover',7,TRUE),
('DV_14','Bàn giao tài nguyên liên quan',8,TRUE),
('DV_14','Kiểm tra sau chuyển giao',9,TRUE),
('DV_15','Xác minh tài khoản doanh nghiệp',1,TRUE),
('DV_15','Cấu hình TikTok Shop',2,TRUE),
('DV_15','Thanh toán / Vận chuyển',3,TRUE),
('DV_15','Cấu trúc danh mục sản phẩm',4,TRUE),
('DV_15','Đăng sản phẩm ban đầu',5,TRUE),
('DV_15','Thiết lập chính sách Shop',6,TRUE),
('DV_15','Affiliate Foundation',7,TRUE),
('DV_15','Tracking / Pixel Integration',8,TRUE),
('DV_15','Test đơn hàng',9,TRUE),
('DV_15','Bàn giao vận hành',10,TRUE),
('DV_15','Tích hợp ERP / OMS',11,FALSE),
('DV_16','Audit TikTok Shop',1,TRUE),
('DV_16','Quản trị danh mục sản phẩm',2,TRUE),
('DV_16','Tối ưu Listing & SEO Shop',3,TRUE),
('DV_16','Giá / Voucher / Khuyến mãi',4,TRUE),
('DV_16','Lịch Campaign thương mại',5,TRUE),
('DV_16','Affiliate / Creator Coordination',6,TRUE),
('DV_16','Phối hợp Content-Commerce',7,TRUE),
('DV_16','Quản trị đơn hàng / CSKH',8,TRUE),
('DV_16','Theo dõi sức khỏe Shop & vi phạm',9,TRUE),
('DV_16','Báo cáo & tối ưu doanh thu',10,TRUE),
('DV_16','Livestream Commerce',11,FALSE),
('DV_16','TikTok Shop Ads',12,FALSE),
('DV_17','Audit Shopee Shop',1,TRUE),
('DV_17','Tối ưu Storefront',2,TRUE),
('DV_17','Quản trị danh mục sản phẩm',3,TRUE),
('DV_17','SEO Listing',4,TRUE),
('DV_17','Giá / Voucher / Combo',5,TRUE),
('DV_17','Tham gia Campaign Shopee',6,TRUE),
('DV_17','Quản trị Chat / CSKH',7,TRUE),
('DV_17','Quản trị đơn hàng & vận hành',8,TRUE),
('DV_17','Theo dõi sức khỏe Shop',9,TRUE),
('DV_17','Báo cáo & tối ưu doanh thu',10,TRUE),
('DV_17','Shopee Ads',11,FALSE),
('DV_18','Brief & Brand Voice',1,TRUE),
('DV_18','Nghiên cứu chủ đề / đối tượng',2,TRUE),
('DV_18','Content Pillars',3,TRUE),
('DV_18','Content Plan',4,TRUE),
('DV_18','Copywriting Social',5,TRUE),
('DV_18','Visual Brief',6,TRUE),
('DV_18','CTA / Hashtag / Format',7,TRUE),
('DV_18','Biên tập & QA',8,TRUE),
('DV_18','Duyệt & chỉnh sửa',9,TRUE),
('DV_18','Bàn giao / Scheduling-ready Assets',10,TRUE),
('DV_18','Đánh giá hiệu suất nội dung',11,FALSE),
('DV_19','PR Brief & mục tiêu truyền thông',1,TRUE),
('DV_19','Thông điệp & PR Angle',2,TRUE),
('DV_19','Media List / Kênh báo chí',3,TRUE),
('DV_19','Outline bài PR',4,TRUE),
('DV_19','Viết bài PR',5,TRUE),
('DV_19','Fact-check / Legal-check nội dung',6,TRUE),
('DV_19','Duyệt nội dung',7,TRUE),
('DV_19','Booking / Media Pitching',8,TRUE),
('DV_19','Theo dõi xuất bản',9,TRUE),
('DV_19','Clipping & Báo cáo',10,TRUE),
('DV_19','Xử lý chỉnh sửa sau xuất bản',11,FALSE),
('DV_19','Crisis Communication Support',12,FALSE))
INSERT INTO public.service_delivery_items(service_id,name,sort_order,is_required,active)
SELECT s.id,d.name,d.sort_order,d.is_required,TRUE
FROM delivery d JOIN public.services s ON s.service_code=d.service_code
WHERE NOT EXISTS (SELECT 1 FROM public.service_delivery_items e WHERE e.service_id=s.id AND lower(btrim(e.name))=lower(btrim(d.name)));
